/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-container-low': '#161b29',
        'primary-fixed': '#dfe2f4',
        'tertiary-container': '#20201d',
        'surface-container-high': '#252a38',
        background: '#0e1320',
        primary: '#c3c6d7',
        'inverse-surface': '#dee2f5',
        'inverse-primary': '#5a5e6d',
        'on-tertiary-fixed-variant': '#474743',
        'surface-dim': '#0e1320',
        'on-surface': '#dee2f5',
        'on-primary-fixed-variant': '#424655',
        'secondary-container': '#af8d11',
        'on-surface-variant': '#c7c6cc',
        'on-primary-container': '#838697',
        'surface-variant': '#2f3443',
        'surface-tint': '#c3c6d7',
        'on-tertiary-fixed': '#1c1c19',
        'on-secondary-fixed': '#241a00',
        'on-tertiary-container': '#898783',
        'on-primary-fixed': '#171b28',
        error: '#ffb4ab',
        secondary: '#e9c349',
        'surface-container-highest': '#2f3443',
        'on-error-container': '#ffdad6',
        'secondary-fixed': '#ffe088',
        'surface-container': '#1a1f2d',
        surface: '#0e1320',
        'on-error': '#690005',
        'on-primary': '#2c303e',
        'primary-container': '#1b1f2c',
        'on-secondary-container': '#342800',
        'primary-fixed-dim': '#c3c6d7',
        'tertiary-fixed': '#e5e2dd',
        outline: '#909096',
        'surface-container-lowest': '#090e1b',
        'surface-bright': '#343948',
        'on-background': '#dee2f5',
        'on-secondary-fixed-variant': '#574500',
        tertiary: '#c8c6c2',
        'inverse-on-surface': '#2b303e',
        'secondary-fixed-dim': '#e9c349',
        'tertiary-fixed-dim': '#c8c6c2',
        'on-tertiary': '#31302d',
        'outline-variant': '#46464c',
        'error-container': '#93000a',
        'on-secondary': '#3c2f00',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-lg': '48px',
        'margin-mobile': '20px',
        'container-max': '1200px',
        'section-padding': '120px',
        'section-padding-mobile': '64px',
        'stack-md': '24px',
        gutter: '32px',
        'stack-sm': '8px',
      },
      fontFamily: {
        'body-lg': ['Manrope', 'sans-serif'],
        'body-md': ['Manrope', 'sans-serif'],
        'label-sm': ['Manrope', 'sans-serif'],
        'headline-lg': ['Playfair Display', 'serif'],
        'headline-md': ['Playfair Display', 'serif'],
        'display-lg': ['Playfair Display', 'serif'],
        'headline-lg-mobile': ['Playfair Display', 'serif'],
        logo: ['Italiana', 'Playfair Display', 'serif'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '1.25', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '500' }],
        'display-lg': ['40px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-desktop': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-desktop': ['48px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md-desktop': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
